spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:~/docksersil
    username: sa
    password:
    driver-class-name: org.j2.Driver
  jpa:
    hibernate:
      ddl-auto: create
