spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:chat_dev
    username: sa
    password:
      driver-class-name: org.j2.Driver
  jpa:
    hibernate:
      ddl-auto: create   # 실행 시 테이블 자동 생성 (개발용: create 또는 update)
    show-sql: true        # SQL 쿼리 콘솔에 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
